wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708114421.759949
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.16.3
      6: 4.37.0
      8:
      - 1
      - 5
      13: linux-x86_64
